/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayQuestionRouteImport } from './routes/today.question'
import { Route as TodayMomentRouteImport } from './routes/today.moment'
import { Route as TodayChallengeRouteImport } from './routes/today.challenge'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayQuestionRoute = TodayQuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => TodayRoute,
} as any)
const TodayMomentRoute = TodayMomentRouteImport.update({
  id: '/moment',
  path: '/moment',
  getParentRoute: () => TodayRoute,
} as any)
const TodayChallengeRoute = TodayChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => TodayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/today': typeof TodayRouteWithChildren
  '/today/challenge': typeof TodayChallengeRoute
  '/today/moment': typeof TodayMomentRoute
  '/today/question': typeof TodayQuestionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/today': typeof TodayRouteWithChildren
  '/today/challenge': typeof TodayChallengeRoute
  '/today/moment': typeof TodayMomentRoute
  '/today/question': typeof TodayQuestionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/today': typeof TodayRouteWithChildren
  '/today/challenge': typeof TodayChallengeRoute
  '/today/moment': typeof TodayMomentRoute
  '/today/question': typeof TodayQuestionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/today'
    | '/today/challenge'
    | '/today/moment'
    | '/today/question'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/today'
    | '/today/challenge'
    | '/today/moment'
    | '/today/question'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/today'
    | '/today/challenge'
    | '/today/moment'
    | '/today/question'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  TodayRoute: typeof TodayRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/question': {
      id: '/today/question'
      path: '/question'
      fullPath: '/today/question'
      preLoaderRoute: typeof TodayQuestionRouteImport
      parentRoute: typeof TodayRoute
    }
    '/today/moment': {
      id: '/today/moment'
      path: '/moment'
      fullPath: '/today/moment'
      preLoaderRoute: typeof TodayMomentRouteImport
      parentRoute: typeof TodayRoute
    }
    '/today/challenge': {
      id: '/today/challenge'
      path: '/challenge'
      fullPath: '/today/challenge'
      preLoaderRoute: typeof TodayChallengeRouteImport
      parentRoute: typeof TodayRoute
    }
  }
}

interface TodayRouteChildren {
  TodayChallengeRoute: typeof TodayChallengeRoute
  TodayMomentRoute: typeof TodayMomentRoute
  TodayQuestionRoute: typeof TodayQuestionRoute
}

const TodayRouteChildren: TodayRouteChildren = {
  TodayChallengeRoute: TodayChallengeRoute,
  TodayMomentRoute: TodayMomentRoute,
  TodayQuestionRoute: TodayQuestionRoute,
}

const TodayRouteWithChildren = TodayRoute._addFileChildren(TodayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  TodayRoute: TodayRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
